### ISSUE TITLE
What pattern for config `utilityUrls`?

### ISSUE THREAD

**Issue by justinholtweb** [putyourlightson/craft-cache-igniter#2]
What is the pattern to include a list of URLs in a local config file for the `utilityUrls` param? I tried a list of comma-delimited URLs but the admin just shows empty rows for all of them in the utility.

![Screen Shot 2023-12-01 at 11 41 24 AM](https://github.com/putyourlightson/craft-cache-igniter/assets/295903/71950d8b-174f-4741-a5ab-2e2753fab729)

**Comment by bencroker** [comment]
It should be a nested array. I just added an example to the config settings file.
https://github.com/putyourlightson/craft-cache-igniter/blob/666db0d133b0a811d12adceadd404349cc6da9f2/src/config.php#L40-L42

**Comment by justinholtweb** [comment]
Perfect thanks Ben!
