### ISSUE TITLE
Getting error logged from GlobalPing api

### ISSUE THREAD

**Issue by justinholtweb** [putyourlightson/craft-cache-igniter#3]
When using the GlobalPing warmer with the standard locations, I am getting errors listed in the log:
`[2023-12-01 09:18:50] Client error: `POST https://api.globalping.io/v1/measurements` resulted in a `400 Bad Request` response: {   "error": {     "type": "validation_error",     "message": "Parameter validation failed.",     "params": {       "loc (truncated...) `

Craft Pro 4.5.11.1
Cache Igniter | 1.1.2

**Comment by bencroker** [comment]
Is there more to that error? The value of the `params` property should display what the actual issue is. If it is truncated in the logs then perhaps you can dump it somewhere?

**Comment by justinholtweb** [comment]
I reduced my Locations settings array to US West and US East since this company only sells in the US and no longer got error logged on warming. I previously had US West, US East, Brazil, Ireland, Germany, India, Singapore, Japan, Australia in the config. I assume one of those locations was erroring.

**Comment by bencroker** [comment]
Must have been. That log error should reveal more, in case you need it in future.

**Comment by bencroker** [comment]
FYI you can get more specific with U.S. cities, for example, if that would be helpful.
